### ISSUE TITLE
Compile error for BVH_SoA::Intersect and BVH4_CPU::Intersect when BVH_USEAVX is not defined

### ISSUE THREAD

**Issue by brendan-duncan** [jbikker/tinybvh#95]
The implementation for these methods is in the BVH_USEAVX section, and cause undefined reference errors when BVH_USEAVX is not defined.

I don't need the intersect methods myself, so dummy implementations for the #ifndef BVH_USEAVX case would be good for me.

**Comment by jbikker** [comment]
This is now resolved; the fix has been pushed to main.

**Comment by hbf17517** [comment]
I get unresolved external symbols for Intersect methods in systems where these methods are not needed (for a non-AVX and non-NEON case)
This issue was introduced in commit 99903546e818addb51ed100569c0dc0f9d3680fc.
Could you re-introduce these empty methods?
Thank you

**Comment by jbikker** [comment]
This should now be fixed. Let me know if you find any issues.
